# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: github-action-preview-environment-controller
  description: Github action  to manage deploy/undeploy for preview environments depends of PR labels
  homepage: https://cloudposse.com/accelerate
  topics: ""

